### ISSUE TITLE
Create sticker image for this pkg (at least for the website)?

### ISSUE THREAD

**Issue by antagomir** [EBI-Metagenomics/MGnifyR#29]

**Comment by TuomasBorman** [comment]
![mgnifyr_logo](https://github.com/EBI-Metagenomics/MGnifyR/assets/60338854/9b942055-f75e-4467-b51b-2ef237ead9e9)

This could be one option

**Comment by TuomasBorman** [comment]
![mgnifyr_logo2](https://github.com/EBI-Metagenomics/MGnifyR/assets/60338854/195b662b-2fc3-4fcb-a372-5b502f13dd20)

**Comment by antagomir** [comment]
Very nice!

Just thinking that the colors could match more closely with the official MGnify outlook?
https://www.ebi.ac.uk/metagenomics

No other comments really, my preference would be the first one.

**Comment by TuomasBorman** [comment]
This is issue is solved. The sticker can be improved if anyone has better idea as I am not an artist
