### ISSUE TITLE
Diversity indices

### ISSUE THREAD

**Issue by mweberr** [EBI-Metagenomics/MGnifyR#5]
Hi,

to do further analyses, such as the calculation of diversity indices, detailed analysis of the taxonomy and visualisation of multiple samples, which analysis tools to you recommend ? Are there tutorials which work on the results of MGnifyR ?

Best,
Michael

**Comment by TuomasBorman** [comment]
Hello, sorry for very late reply. There has been lots of changes and this repository has been moved under EBI. The package is now in Bioconductor, and supporting the cutting-edge tools. We recommend using miaverse.

See the [vignette](https://ebi-metagenomics.github.io/MGnifyR/articles/MGnifyR.html) and [Orchestrating Microbiome Analysis online book](https://microbiome.github.io/OMA/docs/devel/) for more info.
